apiVersion: v1
kind: Service
metadata:
  name: titra-service
  labels:
    app: main
spec:
  selector:
    app: main
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 3000  # Port on Pod
  type: LoadBalancer
