---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.labels }}
spec:
  selector:
    app: {{ .Values.app.labels }}
  ports:
    - name: {{ .Values.app.name }}
      protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.labels }}
spec:
  selector:
    app: {{ .Values.db.labels }}
  ports:
  - name: {{ .Values.db.name }}
    protocol: {{ .Values.db.service.protocol }}
    port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.targetPort }}
